node {
    stage('Clone Repo') {
        git branch: 'main', url: 'https://github.com/prasadrsreddy/shopping-cart.git'
    }

    stage('Build with Maven') {
        def mvnHome = tool(name: 'maven 3.9.10', type: 'maven')
        sh "${mvnHome}/bin/mvn clean package"
    }

    stage('Deploy WAR to Tomcat') {
        sh 'cp target/*.war /opt/tomcat/webapps'
    }

    stage('Restart Tomcat') {
        sh 'sudo /opt/tomcat/bin/shutdown.sh || true'
        sh 'sudo /opt/tomcat/bin/startup.sh'
    }

    stage('Health Check') {
        sh 'curl -I http://localhost:8080/your-app-name/'
    }
}
